### PR TITLE
changed the message in order to be able to deal with yamllinters (who…

### PR DESCRIPTION
**Pull request by jspaaks**
… sort by keyname and thereby mess with what is 'below')

### CODE REVIEW

**Comment by jspaaks** [comment]
I forgot to mention I could not get the tests to work locally (not using ``mkvirtualenv`` like described here https://doi2cff.readthedocs.io/en/latest/contributing.html#types-of-contributions, tried to use ``virtualenv`` instead...no success)

**Comment by sverhoeven** [comment]
Without successful Travis I can not merge the PR. 
Can you try to install locally using [pipenv](https://pipenv.readthedocs.io/en/latest/install/#installing-pipenv)? 
```
pipenv --three shell
pip install -e . -r requirements_dev.txt
doi2cff --help
```

**Comment by sverhoeven** [comment]
Without successful Travis I can not merge the PR. 
Can you try to install locally using [pipenv](https://pipenv.readthedocs.io/en/latest/install/#installing-pipenv)? 
```
pipenv --three shell
pip install -e . -r requirements_dev.txt
doi2cff --help
```

**Comment by jspaaks** [comment]
understandable. 
I tried 
```bash
cd $(mktemp -d)
pip install --user pipenv
pipenv --three shell
git clone https://github.com/citation-file-format/doi2cff.git
cd doi2cff/  
pip install -e . -r requirements_dev.txt
doi2cff --help # works yay
git checkout message
py.test  # errors about pluggy being the wrong version
```
so tool seems to work but pytest fails

**Comment by sverhoeven** [comment]
Can you merge changes from master branch? This should fix the pytest version conflict.

Slighly altered instuctions in CONTRIBUTIONS.rst
```bash
pipenv install -e . -r requirements_dev.txt
pipenv shell
pytest
```

**Comment by jspaaks** [comment]
for the record, I did
```bash
pipenv --three shell
pipenv install -e . -r requirements_dev.txt
```
(hung in the last step, 
```
Adding doi2cff to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

```
)
let's see if/how the travis fails. Update: looks like that works...well fails normally.

**Comment by jspaaks** [comment]
tried following the instructions more better this time
```
# cd <my doi2cff>
# new terminal
pipenv --rm
pipenv install -e . -r requirements_dev.txt
pipenv shell
pytest
# runs the test (but fail, yay)
```

**Comment by jspaaks** [comment]
All good, over to you.

**Pull request merged**
